site_name: Nanobox docs

nav:
  - Home: index.md
  - Getting started: api-docs
  - Clients:
      - Node.js: api-docs/js
  - Browser playground: api-docs/nano-api

theme: material

extra_css:
  - css/extra.css
  -
plugins:
  - render_swagger

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
        permalink: true
