site_name: Nanobox docs
site_url: https://nanobox.cc/
repo_url: https://github.com/nanobox-cc/docs

nav:
  - Home: index.md
  - Getting started: /api-docs
  - Clients:
      - node.js:
        - Introduction: /api-docs/js
        - A transaction: /api-docs/js/transaction
  - Browser playground: /api-docs/nano-api

theme:
  name: material
  features:
    - navigation.instant
extra_css:
  - css/extra.css
plugins:
  - render_swagger

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
        permalink: true

google_analytics:
  - G-DEF3NZ31S5
  - auto
